@BASE_URL = http://localhost:3333/api/

###
GET {{BASE_URL}}/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpZHVzIiwidXNlcl9yb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODMyNDE2MzUsImV4cCI6MTY4MzI0MTY2NX0.LSy0DjTYOjN_6n6MPoq6A5tYouoKnvEENwXjEQWuFAs
###
GET {{BASE_URL}}/users/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpZHVzIiwidXNlcl9yb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODMyMzc4MjcsImV4cCI6MTY4MzIzNzg4N30.gLbXSjP2nLkJsXfOX1SFS6ZJVQRyRIB9fEiQ5H2w64Y